# Generated by Django 2.2 on 2019-08-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_user', to='blog.Myuser'),
        ),
    ]
