# Generated by Django 2.2 on 2019-08-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190809_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='t_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
